feat(dropdown): added checkbox view to dropdown
hellohaptik/relements pull request #390
Opened 2020-10-23 10:47 UTC by kartik0709

Added checkbox view to dropdown

2020-10-26 05:26 UTC, Neha0290 approved these changes

2020-10-26 06:39 UTC, gopal-virtual requested changes

2020-10-26 06:39 UTC, gopal-virtual commented on src/components/Inputs/Dropdown/components/Options/Options.js
> +                {options.map((option, i) => {
Make this part readable.

2020-10-26 06:39 UTC, gopal-virtual commented on src/components/Inputs/Dropdown/Dropdown.js
> +  useCheckbox,
a different name, because `use<Anything>` is mostly understood as Hooks.

2020-10-26 06:39 UTC, gopal-virtual commented on src/components/Inputs/Dropdown/Dropdown.js
> +        onMouseEnter={mouseEnter}
What's behavior here?

2020-10-26 06:39 UTC, gopal-virtual commented on src/components/Inputs/Dropdown/components/UseCheckboxInput/UseCheckboxInput.js
> +import React from "react";
Different component names other than Use, for the same above reason.

2020-10-27 04:38 UTC, kartik0709 commented on src/components/Inputs/Dropdown/components/Options/Options.js
> +                {options.map((option, i) => {
Moved to a separate function

2020-10-27 04:38 UTC, kartik0709 commented on src/components/Inputs/Dropdown/Dropdown.js
> +  useCheckbox,
Sure. Changed to `withCheckbox`

2020-10-27 04:40 UTC, kartik0709 commented on src/components/Inputs/Dropdown/Dropdown.js
> +        onMouseEnter={mouseEnter}
So basically anytime we click outside of the dropdown box i.e on the dropdown options, or elsewhere, `onBlur` gets called. We want the dropdown options to stay open if the user has clicked on an option. And it should close if the user has clicked outside of the options. So basically mouseEnter and mouseLeave lets us know when the user is on the options, and when isn't.

2020-10-27 04:40 UTC, kartik0709 commented on src/components/Inputs/Dropdown/components/UseCheckboxInput/UseCheckboxInput.js
> +import React from "react";
Done. Changed to `WithCheckboxInput`

2020-10-27 06:27 UTC, gopal-virtual approved these changes

2020-11-02 06:26 UTC, Neha0290 approved these changes

2020-11-02 06:34 UTC, sidMulay approved these changes

2020-11-03 04:46 UTC, merged

2021-11-16 06:08 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: