feat(button): added secondary icon
hellohaptik/relements pull request #394
Opened 2020-11-03 10:14 UTC by imankur

Added optional secondary icon view in Button components.

![Screenshot 2020-11-03 at 3 13 25 PM](https://user-images.githubusercontent.com/3414002/97973056-7d33d100-1deb-11eb-8f62-e249684ddc1a.png)

2020-11-03 10:46 UTC, sidMulay commented on src/components/UI/Button/Button.js
> +  secondaryIcon: PropTypes.oneOfType([PropTypes.element]),
1. Would it render our existing Icons if we simple pass the icon's name? 
We can keep it as user's choice. eg. They can just pass 'info' and it would render the info icon or a custom icon element. 

2. Also, what would happen if I pass any other element here?

2020-11-03 11:23 UTC, imankur commented on src/components/UI/Button/Button.js
> +  secondaryIcon: PropTypes.oneOfType([PropTypes.element]),
Good point. Updated. Users can either pass string identifiers supported by relements `<Icon />` tag or custom icon elements.

2020-11-04 09:35 UTC, sidMulay approved these changes

2020-11-05 08:37 UTC, kartik0709 requested changes

2020-11-05 08:37 UTC, kartik0709 commented on src/components/UI/Button/Button.js
> +  showSecondaryIcon: PropTypes.bool,
Can't we decide whether to show or not on the basis of secondaryIcon? Its very weird that i have to pass the flag separately

2020-11-05 08:37 UTC, kartik0709 commented on src/components/UI/Button/Button.js
> +  onSecondaryClick: PropTypes.func,
i thought we weren't doing this.

2020-11-05 08:38 UTC, imankur commented on src/components/UI/Button/Button.js
> +  showSecondaryIcon: PropTypes.bool,
Make sense. Will update.

2020-11-05 08:41 UTC, imankur commented on src/components/UI/Button/Button.js
> +  onSecondaryClick: PropTypes.func,
We had a chat on this with the design team. They came up with this icon after lots of user studies which they did with the people who build bots regularly. They are confident that this is necessary and will work well.

2020-11-06 12:23 UTC, kartik0709 approved these changes

2020-11-09 05:55 UTC, sidMulay approved these changes

2020-11-09 07:39 UTC, merged

2021-11-16 06:08 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: