fix(dropdown): fixed search result reset in dropdown on selection
hellohaptik/relements pull request #398
Opened 2020-12-03 05:13 UTC by kartik0709

## Jira ticket number
BB-2793

## Changelog
- Updated search to not reset on option select

2020-12-03 11:36 UTC, sidMulay submitted a review, later dismissed

2020-12-08 05:09 UTC, Neha0290 approved these changes

2020-12-08 05:35 UTC, sidMulay approved these changes

2020-12-08 05:45 UTC, gopal-virtual requested changes

2020-12-08 05:45 UTC, gopal-virtual commented on src/components/Inputs/Dropdown/Dropdown.js
> +    else if (!withCheckbox) setText("");
Can you add an intermediatory method like `handleSetText` and put all the checks in one place, something like below -
```
const handleSetText = (value) => {
  if(!value) return;
  if (withCheckbox && withSearch && withMultiple) {
      setText("");
  }
  setText(value)
}
```

2020-12-08 05:46 UTC, kartik0709 commented on src/components/Inputs/Dropdown/Dropdown.js
> +    else if (!withCheckbox) setText("");
no need for it

2020-12-08 05:46 UTC, Shivang-Bhandari approved these changes

2020-12-08 05:53 UTC, gopal-virtual approved these changes

2020-12-08 05:54 UTC, merged

2021-11-16 06:08 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: