feat(theme): POC for theming and structure
hellohaptik/relements pull request #414
Opened 2021-01-18 11:07 UTC by sidMulay

Jira: [BB-3099](https://hello-haptik.atlassian.net/browse/BB-3099)

## Changelog

- POC for theming Relements' components
- Only `Button` component has been themed

2021-02-02 08:55 UTC, swapnilmisal requested changes

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/Overlays/Tooltip/ThemedTooltip/ThemedArrow.js
> +const ThemeTooltipArrowColor = variant({
why explicit names for themed components......

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/Overlays/Tooltip/ThemedTooltip/ThemedWrapper.js
> +  transition: "all 0.2s ease",
transition all should be avoided.....

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Button/Button.js
> +import ThemeButton from "./ThemeButton";
This is adding tech-debt, we will have to rename components... later...
we should avoid naming components and themed components

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Button/ThemeButton.js
> +  transition: "all 0.3s ease",
transition all should be avoided...

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Button/__tests__/Button.test.js
> +});
add newline...

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/Table.js
> +          themed
why the Header and Render body translated to themed components, why the prop value is not used?
has this change tested on places where the Table component is used... across our tools...

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/ThemedTable/ThemedHeaderItem.js
> +    noBorder: {},
why no value is treated as an empty object instead of null...

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/ThemedTable/ThemedHeaderItem.js
> +    default: {},
same as above

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/ThemedTable/ThemedHeaderItem.js
> +    compact: {},
same as above

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/ThemedTable/ThemedHeaderItem.js
> +  borderRightColor: "grey.haptik",
the naming thing with. looks very odd, there were other alternatives such as using `-`,
what is the reason for choosing `.`.

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/ThemedTable/ThemedRowItem.js
> +    noBorder: {},
why empty object and not null...

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/ThemedTable/ThemedTableWrapper.js
> +  transition: "all 0.3s ease-in",
avoid transition all

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/ThemedTable/ThemedTableWrapper.js
> +    noBorder: {},
same as above

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/components/Header.js
> +            (sortOrder === 1 ? "▲" : "▼");
this would not always return sort Icon.

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/components/Header.js
> +            (sortOrder === 1 ? "▲" : "▼");
e.g.
1 && false && (1 ? "yes" : "no");

2021-02-02 08:55 UTC, swapnilmisal commented on src/components/UI/Table/components/Row.js
> +                width: widths[i],
why the widths passed here separately in props???
`src/components/UI/Table/components/Header.js`
in header component width is passed in columns array

2021-02-03 06:30 UTC, gopal-virtual commented on src/components/UI/Table/components/Header.js
> +            (sortOrder === 1 ? "▲" : "▼");
unless sortkey and istheSortedcolumn is defined, it won't have sort icon.

2021-02-03 06:31 UTC, gopal-virtual commented on src/components/UI/Table/ThemedTable/ThemedRowItem.js
> +    noBorder: {},
part of styled-system api.
> If you'd still like to keep variant definitions in your theme, but use theme-based style objects, you must add the variants option to the variant function call in your component with at least one variant defined.

2021-02-03 06:32 UTC, gopal-virtual commented on src/components/UI/Table/ThemedTable/ThemedTableWrapper.js
> +    noBorder: {},
answered above

2021-02-03 06:33 UTC, gopal-virtual commented on src/components/UI/Text/Text.js
> +    tertiary: {},
these names are taken from the spec sheet, variants names are not yet finalized, part of POC.

2021-02-03 06:34 UTC, gopal-virtual commented on src/Theme/text.js
> +  tertiary: {
not yet decided, part of poc, will be part of design contract.

2021-02-08 12:33 UTC, sidMulay commented on src/components/Overlays/Tooltip/ThemedTooltip/ThemedArrow.js
> +const ThemeTooltipArrowColor = variant({
Helps us track various nested elements which can be otherwise difficult to access for theming.

2021-02-09 07:42 UTC, sidMulay commented on src/components/UI/Table/ThemedTable/ThemedHeaderItem.js
> +  borderRightColor: "grey.haptik",
The values fetched here are from an object. 

> `export const colors = {
  text: "#000000",
  background: "#ffffff",
  grey: {
    haptik: "#D5D5D5",
 }}`
 
 To fetch `haptik` from grey theme, we used the said denotion.

2021-02-09 12:41 UTC, swapnilmisal approved these changes

2021-02-09 12:41 UTC, swapnilmisal commented on src/components/UI/Text/Text.js
> +    tertiary: {},
ok

2021-02-09 12:41 UTC, swapnilmisal commented on src/Theme/text.js
> +  tertiary: {
ok

2021-02-09 13:03 UTC, imankur approved these changes
Looks Good.

2021-02-09 13:24 UTC, gopal-virtual submitted a review, later dismissed

2021-02-09 13:24 UTC, swapnilmisal submitted a review, later dismissed

2021-02-11 11:13 UTC, swapnilmisal submitted a review, later dismissed

2021-02-11 11:35 UTC, gopal-virtual approved these changes

2021-02-22 05:22 UTC, swapnilmisal requested changes

2021-02-22 05:22 UTC, swapnilmisal commented on src/components/UI/Text/Text.js
> +  fontFamily: `"Proxima Nova", sans-serif`,
why font family is available as a prop?

2021-02-22 05:40 UTC, swapnilmisal approved these changes

2021-02-22 06:45 UTC, imankur approved these changes

2021-02-22 06:47 UTC, merged

2021-11-16 06:08 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: