miscellaneous(pr-template): add PR template, release drafter and mergeable
hellohaptik/relements pull request #433
Opened 2021-03-03 12:11 UTC by sidMulay

Jira: [BB-3380](https://hello-haptik.atlassian.net/browse/BB-3380)

### Changelog

- Add `mergeable.yml`, `pull_request_template.md` and `release-drafter.yml`

2021-03-03 13:17 UTC, ranvijayj approved these changes
LGTM

2021-03-11 08:13 UTC, ranvijayj approved these changes
LGTM

2021-03-11 08:15 UTC, swapnilmisal commented on .github/release-drafter.yml
> +  - release
add a new line here... please @sidMulay

2021-03-11 08:16 UTC, swapnilmisal requested changes

2021-03-11 08:16 UTC, swapnilmisal commented on .github/mergeable.yml
> +        message: 'This PR is work in progress. Cannot be merged yet.'
add a new line here too please.... @sidMulay

2021-03-11 08:25 UTC, swapnilmisal approved these changes

2021-03-12 05:21 UTC, merged

2021-11-16 06:08 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: