improvement(date): add max/min date support to range-picker
hellohaptik/relements pull request #440
Opened 2021-03-11 08:28 UTC by yashasvi13

2021-03-11 08:34 UTC, sidMulay approved these changes

2021-03-11 11:13 UTC, sidMulay submitted a review, later dismissed

2021-03-11 12:18 UTC, swapnilmisal requested changes

2021-03-11 12:18 UTC, swapnilmisal commented on src/components/Inputs/Date/__tests__/Date.basic.test.js
> +    maxDate={maxDate}
There could be four different variations to write the tests. for min and max data

2021-03-11 12:18 UTC, swapnilmisal commented on src/components/Inputs/Date/components/RangeComparison/RangePicker.js
> +  maxDate: dayjs(),
For a better developer experience,  if a developer do not pass min or max date, the selection of range should not be limited in any way.

2021-03-11 12:18 UTC, swapnilmisal commented on src/components/Inputs/Date/Date.mdx
> +      maxDate={dayjs().add(7, "d")}
Please add more variations for better developer experience.

2021-03-11 12:54 UTC, yashasvi13 commented on src/components/Inputs/Date/components/RangeComparison/RangePicker.js
> +  maxDate: dayjs(),
default value of max/min Date is already defined in the parent component as null, so it was not taking default value of its own component when max/min date is not passed, it simply takes null, so basically having default value of max/min in child component is useless

2021-03-12 05:24 UTC, gopal-virtual requested changes

2021-03-12 05:24 UTC, gopal-virtual commented on src/components/Inputs/Date/components/RangeComparison/RangePicker.js
> +  minDate: PropTypes.object,
call it `instanceOf(Date)`

2021-03-12 06:09 UTC, yashasvi13 commented on src/components/Inputs/Date/components/RangeComparison/RangePicker.js
> +  minDate: PropTypes.object,
Done

2021-03-12 06:42 UTC, gopal-virtual submitted a review, later dismissed

2021-03-12 07:14 UTC, sidMulay approved these changes

2021-03-12 07:18 UTC, yashasvi13 commented on src/components/Inputs/Date/__tests__/Date.basic.test.js
> +    maxDate={maxDate}
Done

2021-03-12 08:12 UTC, swapnilmisal approved these changes

2021-03-12 08:13 UTC, gopal-virtual approved these changes

2021-03-12 08:19 UTC, merged

2021-03-12 08:53 UTC, yashasvi13 commented
Reopening PR for checks

2021-11-16 06:08 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: