fix(date-picker): disable dates before start date, set max selectable compare dates
hellohaptik/relements pull request #444
Opened 2021-03-15 07:08 UTC by yashasvi13

…table compare date

### JIRA Ticket

Jira:  [1150](https://hello-haptik.atlassian.net/browse/AN-1150)

--

### Changelog

Disabled dates before start date, set max selectable compare dates

2021-03-15 08:28 UTC, sidMulay requested changes

2021-03-15 08:28 UTC, sidMulay commented on src/components/Inputs/Date/components/RangeComparison/RangePicker.js
> +    }
- Please add a comment as to what is happening here.
- Call `setState` in the `if(newCompare)` block only once. Since the values for `comparisonStartDate` and `comparisonEndDate` are being updated, declare couple of variables and assign them to start and end date states respectively.

2021-03-15 08:28 UTC, sidMulay commented on src/components/UI/Calendar/Calendar.js
> +      dayjs(value[0].from).isAfter(day)
What is `value[0]`? Does it have to be 0th index?

2021-03-15 08:28 UTC, sidMulay commented on src/components/Inputs/Date/Date.mdx
> +  defaultValue={{ startDate: dayjs().subtract(7, "d"), endDate: dayjs() }}
- Are we considering present day as end date and last 7 days as start date? 
- If yes, any reason why other way round doesn't work?

2021-03-15 08:48 UTC, yashasvi13 commented on src/components/Inputs/Date/components/RangeComparison/RangePicker.js
> +    }
setState is called once only, else updated

2021-03-15 09:12 UTC, yashasvi13 commented on src/components/UI/Calendar/Calendar.js
> +      dayjs(value[0].from).isAfter(day)
value is an array with startDate and endDate, updated it to start/end date itself

2021-03-15 09:16 UTC, yashasvi13 commented on src/components/Inputs/Date/Date.mdx
> +  defaultValue={{ startDate: dayjs().subtract(7, "d"), endDate: dayjs() }}
Yes, it's just a use case we need in analytics, other way round also works

2021-03-15 09:47 UTC, gopal-virtual approved these changes

2021-03-15 09:58 UTC, sidMulay commented on src/components/Inputs/Date/components/RangeComparison/RangePicker.js
> +    }
let comparisionStart = null; let comparisionEnd = null;

if(newCompare && startDate && endDate){
 ...
 comparisionStart = ...
 comparisionEnd = ...
}

this.setState({
   comparisonStartDate: comparisionStart, 
   comparisonEndDate: comparisionEnd
})


----

^ Using this, you'll just update the values when available and use setState only once.

2021-03-15 10:20 UTC, sidMulay approved these changes

2021-03-15 10:54 UTC, gopal-virtual approved these changes

2021-03-15 10:59 UTC, merged

2021-03-15 12:08 UTC, swapnilmisal commented on src/components/UI/Calendar/Calendar.js
> +  comparisonMaxDate: undefined,
we should not set something as undefined, as the value not defined is already undefined,
in the default props, we want to set a value if the value is undefined.
so here the appropriate value would be `null`.
by doing that we know that this value is set in default props,
the similar thing holds for default arguments.

2021-11-16 06:08 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: