fix(calendar): toggle calendar to selected button
hellohaptik/relements pull request #448
Opened 2021-03-17 10:21 UTC by yashasvi13

### JIRA Ticket

Jira:  1150

--

### Changes
Toggle calendar to selected month on any shortcut button clicked

2021-03-17 10:54 UTC, gopal-virtual requested changes

2021-03-17 10:54 UTC, gopal-virtual commented on src/components/UI/Calendar/Calendar.js
> +  }, [comparisonStartDate]);
shouldn't the effect be triggered when the user selects the end date?

2021-03-17 11:03 UTC, yashasvi13 commented on src/components/UI/Calendar/Calendar.js
> +  }, [comparisonStartDate]);
We don't really select the end date for comparison, it gets calculated according to the date range.

2021-03-17 11:13 UTC, gopal-virtual approved these changes

2021-03-18 04:37 UTC, swapnilmisal approved these changes

2021-03-18 04:54 UTC, merged

2021-11-16 06:07 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: