feat(checkbox): incorporate design system colors in checkbox component
hellohaptik/relements pull request #449
Opened 2021-03-18 11:46 UTC by murtazamzk

### JIRA Ticket

Jira: BB-3527

### Changelog

Add design system colors to checkbox

2021-04-12 16:22 UTC, sidMulay requested changes

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/ThemedCheckbox/ThemedCheckboxItem.js
> +        background-color: ${props => props.value ? (props.disabled ? colors.grey.deep : colors.blue.dark) : colors.background};
Prevent nesting ternary expressions

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/ThemedCheckbox/ThemedCheckboxItem.js
> +        border-radius: 4px;
Use values from design system here. They will be available to you via `props`

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/ThemedCheckbox/ThemedCheckboxItem.js
> +        height: 16px;
Same as above.

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/ThemedCheckbox/ThemedCheckboxItem.js
> +        opacity: ${props => props.value ? "1" : "0"};
Values don't need to be a string.

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/components/CheckboxOption.js
> +          background: themed ? (disabled ? colors.grey.deep : colors.blue.dark) : primaryColor,
Prevent ternary nesting

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/components/CheckboxOption.js
> +          borderColor: themed ? (disabled ? colors.grey.deep : colors.blue.dark) : primaryColor,
Same as above

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/components/CheckboxOption.js
> +          background: themed ? colors.background : null,
Can we not use 'transparent' instead of null?

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/components/CheckboxOption.js
> +          borderColor: themed ? (disabled ? colors.grey.deep : colors.blue.dark) : null,
Prevent ternary nesting. Observed multiple times. Please rectify this wherever applicable.

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/components/CheckboxOption.js
> +          color: themed ? colors.grey.deep : null,
Can we use 'transparent' here as well? If not, then don't pass the color property only.

2021-04-12 16:22 UTC, sidMulay commented on src/components/Inputs/Checkbox/components/CheckboxOption.scss
> +  height: 16px;
Why are we making changes in the scss file?

2021-04-13 05:12 UTC, murtazamzk commented on src/components/Inputs/Checkbox/ThemedCheckbox/ThemedCheckboxItem.js
> +        border-radius: 4px;
This values are fixed wont be configurable

2021-04-13 11:01 UTC, gopal-virtual requested changes

2021-04-13 11:01 UTC, gopal-virtual commented on src/components/Inputs/Checkbox/ThemedCheckbox/ThemedCheckboxItem.js
> +import { colors } from "@src/Theme/colors";
you should not import color tokens directly here. That's an anti-pattern.

2021-04-13 11:01 UTC, gopal-virtual commented on src/components/Inputs/Checkbox/ThemedCheckbox/ThemedCheckboxItem.js
> +  background-color: ${props => props.value ? iff(props.disabled, colors.grey.deep, colors.blue.dark) : colors.background};
access colors via `props.theme.colors` instead

2021-04-14 07:14 UTC, murtazamzk commented on src/components/Inputs/Checkbox/Checkbox.js
> +              prefixClassName={`${prefixClassName}-option`}
This is the old checkbox component

2021-04-14 10:29 UTC, gopal-virtual approved these changes

2021-04-14 11:01 UTC, sidMulay approved these changes

2021-04-14 11:16 UTC, merged

2021-11-16 06:07 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: