feat(tooltip): add stories to tooltip w/ design system
hellohaptik/relements pull request #450
Opened 2021-03-18 12:04 UTC by sidMulay

### JIRA Ticket

Jira:  [BB-3342](https://hello-haptik.atlassian.net/browse/BB-3342)

--

### Changelog

- Add stories to tooltip component and its usage with design system

--

2021-03-23 09:39 UTC, gopal-virtual requested changes

2021-03-23 09:39 UTC, gopal-virtual commented on src/Theme/tooltip.js
> -    borderTopColor: "#28394b !important",
use color token

2021-03-23 09:39 UTC, gopal-virtual commented on src/Theme/tooltip.js
> +    fontSize: 12,
use font size token

2021-03-23 09:39 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/Tooltip.js
> +  if (!toggleWithHover && (!attachTo || !enabled)) return null;
what's  the use?

2021-03-23 09:39 UTC, gopal-virtual commented on src/hooks/usePositioner/usePositioner.js
> +        coordinates.top = rect.top - 3;
use rect's height and calculate center, same goes for right. Also, keep all the padding in one constant, so we can manage spacing from one place. You can use a space token for the same.

2021-03-23 09:39 UTC, gopal-virtual commented on src/components/Overlays/WithTooltip/WithTooltip.js
> +  const tooltipContentClassName = `${styles.withTooltip} ${prefixClassName}-inner-wrapper`;
why are we using classNames?

2021-03-23 09:39 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/Tooltip.js
> +    attachTo: toggleWithHover ? DOMRef : attachTo,
can we get rid of `attachTo`?

2021-03-23 09:39 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/ThemedTooltip.js
> +const ThemeTooltipArrowColor = variant({
just name it colorVariant, and positionVariant.

2021-03-23 09:39 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/Tooltip.js
> +      </Portal>
do you think we need portals for the tooltip?

2021-03-23 09:44 UTC, sidMulay commented on src/components/Overlays/Tooltip/Tooltip.js
> +  if (!toggleWithHover && (!attachTo || !enabled)) return null;
When `toggleWithHover` is passed,  `attachTo` will be of no use to us since ref will be created internally and `enabled` is also redundant since it tooltip will trigger on hover.

2021-03-23 09:45 UTC, sidMulay commented on src/components/Overlays/WithTooltip/WithTooltip.js
> +  const tooltipContentClassName = `${styles.withTooltip} ${prefixClassName}-inner-wrapper`;
This is just refactor of WithTooltip's existing code.

2021-03-23 09:48 UTC, sidMulay commented on src/components/Overlays/Tooltip/Tooltip.js
> +    attachTo: toggleWithHover ? DOMRef : attachTo,
Tooltip relies on this prop. In the event of assigning tooltip to a button component, this prop comes in handy to identify where to display the tooltip. Like we have in our Tooltip.mdx.

2021-03-23 09:50 UTC, sidMulay commented on src/components/Overlays/Tooltip/Tooltip.js
> +      </Portal>
Love the fact that it clears the DOM once the use of tooltip is done and re-creates it when its needed. I suppose we can come up with some custom util method to provide a similar functionality. But as of now, this seems like a good option.

2021-03-23 09:53 UTC, sidMulay commented on src/Theme/tooltip.js
> -    borderTopColor: "#28394b !important",
This block is removed already.

2021-03-23 09:53 UTC, sidMulay commented on src/Theme/tooltip.js
> -    borderTopColor: "#28394b !important",
This code block is removed.

2021-03-23 10:33 UTC, yashasvi13 approved these changes

2021-03-23 11:07 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/Tooltip.js
> +    attachTo: toggleWithHover ? DOMRef : attachTo,
But why can't we assume that tooltip will always be attached to its children?

2021-03-23 11:07 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/Tooltip.js
> +  if (!toggleWithHover && (!attachTo || !enabled)) return null;
we should ideally use this behavior with click also.
```
<Tooltip trigger="click" text="Tooltip text">
  <Button>Click</Button>
</Tooltip>
```

2021-03-23 11:07 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/Tooltip.js
> +      </Portal>
the reason for this suggestion is to fix the scroll behavior. If we can attach the tooltip as a sibling which is positioned absolutely in a relative parent, then we don't need to figure the scrolling issue.

2021-03-23 11:07 UTC, gopal-virtual commented on src/components/Overlays/WithTooltip/WithTooltip.js
> +  const tooltipContentClassName = `${styles.withTooltip} ${prefixClassName}-inner-wrapper`;
got it

2021-03-23 11:10 UTC, sidMulay commented on src/components/Overlays/Tooltip/Tooltip.js
> +    attachTo: toggleWithHover ? DOMRef : attachTo,
Because the component can be outside of tooltip as well. 

eg. 
```
      <Button
        innerRef={ref}
        onClick={...}
      >
        Open Tooltip
      </Button>

      <Tooltip
        themed
        attachTo={ref}
      >
        <div>'sup?</div>
      </Tooltip>
```

2021-03-23 15:21 UTC, sidMulay commented on src/components/Overlays/Tooltip/Tooltip.js
> +      </Portal>
Added dismiss on scroll. Resolving this.

2021-03-24 05:13 UTC, gopal-virtual requested changes

2021-03-24 05:13 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/ThemedTooltip.js
> +  variants: {},
I believe this will not work properly, you have to mention at least one variant as a blank object ( I always add all variants with a blank object).  https://styled-system.com/variants
> If you'd still like to keep variant definitions in your theme, but use theme-based style objects, you must add the variants option to the variant function call in your component with at least one variant defined.

2021-03-24 05:13 UTC, gopal-virtual commented on src/Theme/tooltip.js
> +    margin: "0 0 0 -1px",
can you use space tokens for margin, top, and left.

2021-03-24 05:13 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/ThemedTooltip.js
> +  padding: 0,
use `padding: 'zero'`

2021-03-24 05:13 UTC, gopal-virtual commented on src/components/Overlays/Tooltip/Tooltip.js
> +              window.addEventListener("scroll", handleScroll, {
this needs to be removed as well.

2021-03-24 05:13 UTC, gopal-virtual commented on src/hooks/usePositioner/usePositioner.js
> +        coordinates.left = rect.left - tooltipRect.width - 10;
can we use padding tokens instead of 10 hard coded?

2021-03-24 05:13 UTC, gopal-virtual commented on src/hooks/usePositioner/usePositioner.js
> +        coordinates.left = rect.left - tooltipRect.width - 10;
or do you think it should be local?

2021-03-24 05:57 UTC, sidMulay commented on src/hooks/usePositioner/usePositioner.js
> +        coordinates.left = rect.left - tooltipRect.width - 10;
Making a local constants file.

2021-03-24 06:04 UTC, gopal-virtual approved these changes

2021-03-24 06:05 UTC, yashasvi13 approved these changes

2021-03-24 06:07 UTC, merged

2021-11-16 06:07 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: