feat(dropdown): integrate design system w/dropdown
hellohaptik/relements pull request #461
Opened 2021-03-25 19:31 UTC by sidMulay

### JIRA Ticket

Jira:  [BB-3348](https://hello-haptik.atlassian.net/browse/BB-3348)

--

### Changelog

- Integrated `Text` component w/design system
- Integrated `Label` component w/design system
- Integrated `Dropdown` component w/design system
- Integrated `ChipsInput` component w/design system

--

### Test Link:

2021-04-08 05:28 UTC, gopal-virtual requested changes

2021-04-08 05:28 UTC, gopal-virtual commented on src/components/Inputs/Dropdown/components/Options/Options.js
> +  noOptionsText,
why is it passed as a prop? Kind of overkill.

2021-04-08 05:28 UTC, gopal-virtual commented on src/components/Inputs/Text/Text.mdx
> +import Text from "./Text";
We will have to rename this, Now we have two Text components.

2021-04-08 05:28 UTC, gopal-virtual commented on src/components/Inputs/_common/ChipsInput.js
> +      : `${styles.themedNewChip} ${value.length > 0 &&
we shouldn't be using css for themed ones

2021-04-08 05:28 UTC, gopal-virtual commented on src/components/Inputs/_common/Label.js
> +          <ThemedLabel mode={mode}>
can we not use Text here?

2021-04-08 05:28 UTC, gopal-virtual commented on src/components/Inputs/_common/TextInput.js
> +          <ThemedTextInputWrapper mode={inputWrapperMode}>
Use Box

2021-04-08 16:56 UTC, sidMulay commented on src/components/Inputs/_common/ChipsInput.js
> +      : `${styles.themedNewChip} ${value.length > 0 &&
Yeah, hence added a comment here. 
We are using `react-input-autosize` - an external library here. To control its styles, we have used classes.

2021-04-09 04:52 UTC, sidMulay commented on src/components/Inputs/Dropdown/components/Options/Options.js
> +  noOptionsText,
`noOptionsText` is passed here so that we can apply the error style i.e. color Haptik Red. Attaching the logic for reference:

> ` <Text
            variant="body.md"
            color={children === noOptionsText && "red.haptik"}
          >
            {children}
          </Text>`

2021-04-09 04:55 UTC, sidMulay commented on src/components/Inputs/_common/Label.js
> +          <ThemedLabel mode={mode}>
We can, but `ThemedLabel` has its own custom modes, which are specifically meant for Label only.

2021-04-09 07:51 UTC, sidMulay commented on src/components/Inputs/Text/Text.mdx
> +import Text from "./Text";
Have created a ticket to track this: https://hello-haptik.atlassian.net/browse/BB-3837

2021-04-09 14:06 UTC, yashasvi13 approved these changes

2021-04-14 07:27 UTC, gopal-virtual requested changes

2021-04-14 07:27 UTC, gopal-virtual commented on src/components/Inputs/Dropdown/components/Options/Options.js
> +      window.removeEventListener("scroll", handleScroll);
remove scroll listener on unmount
```
useEffect(()=>{
  // add listener
  window.addEventListener()

  // unmount - remove
  return () => window.removeEventListener()
})
```

2021-04-14 08:04 UTC, gopal-virtual approved these changes

2021-04-14 08:48 UTC, yashasvi13 approved these changes

2021-04-14 08:50 UTC, merged

2021-11-16 06:07 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: