improvement(table): add rowBackground prop
hellohaptik/relements pull request #472
Opened 2021-04-13 10:21 UTC by swapnilmisal

### JIRA Ticket

Jira:  [AGCT-1096](https://hello-haptik.atlassian.net/browse/AGCT-1096)

--

### Changelog

rowBackground prop enables alternate row background style

--

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/11783611/114537631-10611480-9c70-11eb-9d8d-c30570ce4248.png)

2021-04-13 12:42 UTC, gopal-virtual approved these changes

2021-04-14 12:25 UTC, gopal-virtual requested changes

2021-04-14 12:25 UTC, gopal-virtual commented on src/components/Context/Theme.storybook.js
> +      <Table themed space="sparse" {...tableProps} />
variant should match what designers have defined.

2021-04-14 12:40 UTC, swapnilmisal commented on src/components/Context/Theme.storybook.js
> +      <Table themed space="sparse" {...tableProps} />
I don't see a problem here,
1. the quick resolutions could be that, I'll remove sparse and put this spacing in the default.
2. or I'll remove the sparse altogether and its spacing,-- but then some features will have to wait until the spacing is fixed

2021-04-15 06:12 UTC, gopal-virtual approved these changes

2021-04-15 06:43 UTC, AwadheshJha approved these changes

2021-04-15 06:44 UTC, sidMulay approved these changes

2021-04-15 07:36 UTC, swapnilmisal commented
RETEST THIS PLEASE!

2021-04-15 07:57 UTC, merged

2021-11-16 06:07 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: