feat(tabs): migrate to new design systems
hellohaptik/relements pull request #486
Opened 2021-05-06 07:31 UTC by swapnilmisal

### JIRA Ticket

Jira:  [AGCT-1225](https://hello-haptik.atlassian.net/browse/AGCT-1225)

--

### Changelog

- Migrate Tabs component to new design systems

--

### Screenshots (if appropriate):

-- Changes in Relements

![image](https://user-images.githubusercontent.com/11783611/117257643-bf58d080-ae69-11eb-836d-9670c45f1d86.png)

Test Link: https://devswapnil.hellohaptik.com/relements/?path=/story/components-ui-tabs--documentation

2021-05-06 10:25 UTC, sidMulay requested changes

2021-05-06 10:25 UTC, sidMulay commented on src/components/UI/Tabs/Tabs.js
> +          style={{
Why are we using inline style here? Add `modes` or `variants` to achieve this.

2021-05-06 10:25 UTC, sidMulay commented on src/components/UI/Tabs/ThemedTabs.js
> +const ThemedTabs = styled("div")(tabsStyle);
Instead of `styled("div")` use `styled('Box')` wherever there's a wrapper or a div, it will always be hooked to the design system.

2021-05-06 10:25 UTC, sidMulay commented on src/components/UI/Tabs/ThemedTabs.js
> +const ThemedTabsIndicator = styled("div")(tabsIndicatorStyle);
Same as above

2021-05-06 10:25 UTC, sidMulay commented on src/components/UI/Tabs/components/TabsItem.js
> +                className={`${styles.TabsItemIcon} ${bigClassName} ${prefixClassName}-icon ${activeIconClassName}`}
Add a TODO above this to use design system's Icon component whenever that will be migrated.

2021-05-06 10:25 UTC, sidMulay commented on src/components/UI/Tabs/components/ThemedTabsItem.js
> +const ThemedTabsItems = styled("div")(tabsItemsStyle);
Use Box here as well.

2021-05-06 13:31 UTC, swapnilmisal commented on src/components/UI/Tabs/components/TabsItem.js
> +            {icon ? (
No need to refactor, since one part of the code has to be removed.

2021-05-06 13:31 UTC, swapnilmisal commented on src/components/UI/Tabs/components/TabsItem.js
> +                className={`${styles.TabsItemIcon} ${bigClassName} ${prefixClassName}-icon ${activeIconClassName}`}
done

2021-05-06 17:47 UTC, swapnilmisal commented on src/components/UI/Tabs/Tabs.js
> +          style={{
removed the intline style

2021-05-07 09:32 UTC, swapnilmisal commented on src/components/UI/Tabs/ThemedTabs.js
> +const ThemedTabsIndicator = styled("div")(tabsIndicatorStyle);
done

2021-05-07 09:32 UTC, swapnilmisal commented on src/components/UI/Tabs/ThemedTabs.js
> +const ThemedTabs = styled("div")(tabsStyle);
done

2021-05-07 09:32 UTC, swapnilmisal commented on src/components/UI/Tabs/components/ThemedTabsItem.js
> +const ThemedTabsItems = styled("div")(tabsItemsStyle);
done

2021-05-07 10:01 UTC, sidMulay submitted a review, later dismissed

2021-05-07 10:40 UTC, gopal-virtual requested changes

2021-05-07 10:40 UTC, gopal-virtual commented on src/components/UI/Tabs/components/ThemedTabsItem.js
> +  display: "flex",
not required

2021-05-07 10:40 UTC, gopal-virtual commented on src/components/UI/Tabs/components/ThemedTabsItem.js
> +  paddingBottom: props.theme.space.sm,
you can use paddingY and paddingX

2021-05-07 10:40 UTC, gopal-virtual commented on src/components/UI/Tabs/Tabs.mdx
> +      <Tabs.Item value="bots" onClick={setValue} icon="bot-says" disabled>
default selection should not be disabled

2021-05-07 10:40 UTC, gopal-virtual commented on src/components/UI/Tabs/Tabs.mdx
> +### Themed without Icons
are we not adding a button like tab variation, as you have used in agent chat?

2021-05-07 11:40 UTC, swapnilmisal commented on src/components/UI/Tabs/Tabs.mdx
> +### Themed without Icons
No

2021-05-07 11:45 UTC, swapnilmisal commented on src/components/UI/Tabs/components/ThemedTabsItem.js
> +  display: "flex",
done

2021-05-07 11:45 UTC, swapnilmisal commented on src/components/UI/Tabs/components/ThemedTabsItem.js
> +  paddingBottom: props.theme.space.sm,
done..

2021-05-07 11:46 UTC, swapnilmisal commented on src/components/UI/Tabs/Tabs.mdx
> +      <Tabs.Item value="bots" onClick={setValue} icon="bot-says" disabled>
removed this variation.

2021-05-07 12:23 UTC, swapnilmisal commented on src/components/UI/Tabs/components/ThemedTabsItem.js
> +  display: "flex",
removed

2021-05-07 13:01 UTC, gopal-virtual approved these changes

2021-05-07 13:15 UTC, yashasvi13 approved these changes

2021-05-07 13:16 UTC, merged

2021-11-16 06:06 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: