feat(radio): add design component for Radio
hellohaptik/relements pull request #494
Opened 2021-05-11 04:26 UTC by gopal-virtual

## Jira
https://hello-haptik.atlassian.net/browse/AN-1461

## Changes
- Migrate Radio to new design system variants
- Add new API for Radio

## Test
https://relements-gopalojha-haptik-test.vercel.app/?path=/story/components-inputs-radio--design-components

2021-05-17 05:17 UTC, sidMulay requested changes

2021-05-17 05:17 UTC, sidMulay commented on src/components/Inputs/Radio/components/Themed/RadioItem.js
> +const RadioIconOuter = styled("div")(
Can we use `Box` here?

2021-05-17 05:17 UTC, sidMulay commented on src/components/Inputs/Radio/components/Themed/RadioItem.js
> +      <RadioText variant="body.lg" {...designProps}>
Will the text size always be `body.lg`?

2021-05-17 06:14 UTC, gopal-virtual commented on src/components/Inputs/Radio/components/Themed/RadioItem.js
> +      <RadioText variant="body.lg" {...designProps}>
Yes, that's how the current contract specify

2021-05-17 06:16 UTC, gopal-virtual commented on src/components/Inputs/Radio/components/Themed/RadioItem.js
> +const RadioIconOuter = styled("div")(
The default Box is not a good place to start to make it a Radio Icon. Box is ideal where a lot of it can be easily inherited, e.g. Layouts

2021-05-17 08:27 UTC, sidMulay requested changes

2021-05-17 08:27 UTC, sidMulay commented on src/components/Inputs/Radio/Radio.js
> +            className={`${prefixClassName}-label`}
- We don't need `className` here
- Pass `themed` prop to Label component, it is rendering older label currently

![image](https://user-images.githubusercontent.com/65707346/118457905-da53fc00-b717-11eb-877a-816b9ea1894a.png)

2021-05-17 10:06 UTC, gopal-virtual commented on src/components/Inputs/Radio/Radio.js
> +            className={`${prefixClassName}-label`}
my bad, updating

2021-05-18 05:02 UTC, sidMulay approved these changes

2021-05-18 05:18 UTC, merged

2021-11-16 06:06 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: