enhancement(dropdown): variant with a prefix icon
hellohaptik/relements pull request #502
Opened 2021-06-10 10:23 UTC by yashasvi13

### JIRA Ticket 

Jira:  [AN-1715](https://hello-haptik.atlassian.net/browse/AN-1715)

--

### Changelog
- Dropdown variant with a prefix icon

2021-06-10 11:00 UTC, sidMulay requested changes

2021-06-10 11:00 UTC, sidMulay commented on src/components/Inputs/Dropdown/Dropdown.js
> +            prefixIcon={prefixIcon}
Do we need `prefixIcon` for older (non-themed) dropdown?

2021-06-10 11:00 UTC, sidMulay commented on src/components/Inputs/Dropdown/ThemedDropdown.js
> +const DropdownPrefix = styled("div")(
- Use `Box` here and re-style it per your needs.
- Rename it to `DropdownPrefixIcon`

2021-06-10 11:00 UTC, sidMulay commented on src/components/Inputs/Dropdown/components/Input/Input.js
> +  ) : null;
themedPrefixIcon && <Icon .../>, no need of ternary operator here.

2021-06-10 11:00 UTC, sidMulay commented on src/components/Inputs/Dropdown/components/Input/Input.js
> +      />
Do we need to use `className` and `prefixClassName` here?

2021-06-10 11:00 UTC, sidMulay commented on src/components/Inputs/Dropdown/components/Input/Input.scss
> +  }
We don't need to make changes in scss file. Make the style changes in in `DropdownPrefix` via Design System. Refer to `DropdownArrow`

2021-06-11 07:51 UTC, sidMulay submitted a review, later dismissed

2021-06-11 10:03 UTC, gopal-virtual approved these changes

2021-06-11 10:11 UTC, sidMulay approved these changes

2021-06-11 10:19 UTC, merged

2021-11-16 06:06 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: