improvement: size variant for input/dropdown
hellohaptik/relements pull request #505
Opened 2021-06-15 12:30 UTC by yashasvi13

### JIRA Ticket

Jira:  [AN-1715](https://hello-haptik.atlassian.net/browse/AN-1715)

--

### Changelog

Size variant small for input and integrated for dropdown

2021-06-16 05:12 UTC, sidMulay requested changes

2021-06-16 05:12 UTC, sidMulay commented on src/components/Inputs/Dropdown/Dropdown.js
> +              size={size}
If we're only adding a small within the size variant, would it work if we only name the prop as a flag? 
eg. prop can be a boolean like just `small`. If dev adds `small` to the dropdown, it'll render smaller one.

2021-06-16 05:12 UTC, sidMulay commented on src/components/Inputs/Text/Text.js
> +        size={size}
Same as above.

2021-06-16 05:12 UTC, sidMulay commented on src/components/Inputs/_common/ThemedTextInput.js
> +  size: "",
Why was this added here? I can see that some padding has been added to the textarea

2021-06-16 05:12 UTC, sidMulay commented on src/Theme/textInput.js
> +    padding: `${space.sm}px ${space.lg - space.sm}px`,
Are we only reducing padding and not the font size?

2021-06-16 05:17 UTC, yashasvi13 commented on src/Theme/textInput.js
> +    padding: `${space.sm}px ${space.lg - space.sm}px`,
Yeah fontsize remains the same

2021-06-16 06:16 UTC, sidMulay commented on src/components/Inputs/Dropdown/Dropdown.js
> +              size={size}
As discussed, this suggestion is parked for now since size can possibly expand to large

2021-06-16 08:24 UTC, sidMulay approved these changes

2021-06-17 10:33 UTC, merged

2021-11-16 06:06 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: