fix(dropdown): onClick with search input in dropdown
hellohaptik/relements pull request #522
Opened 2021-07-19 04:51 UTC by raushan303

### JIRA Ticket

Jira:  [AGCT-1365](https://hello-haptik.atlassian.net/browse/AGCT-1365)

### Changelog
- there is two events onBlur and onClick 
- when someone click this div, we want first onClick to dispatch first but here onBlur get dispatch first
- that's why we have put logic inside setTimeout with time 100ms hoping in this time onClick will get dispatched
- but 100ms doesn't seems enough, so i have increased it to 200ms and it's working fine.

2021-07-19 05:27 UTC, swapnilmisal requested changes

2021-07-19 05:27 UTC, swapnilmisal commented on src/components/Inputs/Dropdown/Dropdown.js
>      // the delay is non-consequential as it's only there when the input resets
This way of implementation doesn't seem to be a nice way, of implementation.
it feels like it is delay-dependent for correct render.
The implementation is non-deterministic because the actual delay value could be different for different machines, to correctly render something.

This is very difficult to reason about,
@sidMulay @gopal-virtual 

anyways this setTimeout will only execute post there is nothing on the stack to execute.
@raushan303 how does this delay fixes the issue?

2021-07-19 05:36 UTC, raushan303 commented on src/components/Inputs/Dropdown/Dropdown.js
>      // the delay is non-consequential as it's only there when the input resets
ya exactly we want it to execute post there is nothing on stack to execute and that fixes our issue
for event to get dispatch sequence is
1. onMouseDown 
2. onBlur
3. onClick
but we want onClick to dispatch first, one way of doing it is putting it inside setTimeout
there is also another way by using onMouseDown by preventing default action there
we have to add `onMouseDown = {e => e.preventDefault()}`
this way first onClick will get executed then onBlur this will also fix the issue

2021-07-19 05:42 UTC, raushan303 commented
https://www.programmersought.com/article/24691658235/
https://stackoverflow.com/questions/17769005/onclick-and-onblur-ordering-issue
![Screenshot from 2021-07-19 11-11-36](https://user-images.githubusercontent.com/43717503/126108603-113bfdd8-d5cf-4628-83bd-7ba40d637872.png)

2021-07-19 05:43 UTC, swapnilmisal commented on src/components/Inputs/Dropdown/Dropdown.js
>      // the delay is non-consequential as it's only there when the input resets
@raushan303 
does `onMouseDown = {e => e.preventDefault()}` does this approach covers all the cases?

2021-07-19 05:58 UTC, gopal-virtual requested changes

2021-07-19 05:58 UTC, gopal-virtual commented on src/components/Inputs/Dropdown/Dropdown.js
> +    withCreate,
any reason, you've added so many dependencies. Can you add a comment about the same?

2021-07-19 06:05 UTC, swapnilmisal commented on src/components/Inputs/Dropdown/Dropdown.js
>      // the delay is non-consequential as it's only there when the input resets
@raushan303 
https://stackoverflow.com/questions/17769005/onclick-and-onblur-ordering-issue

^^ can you read this thread and all its comments and come out with a robust solution.
also, you can notice that one implementation with SetTimeout is negatively voted.

2021-07-19 06:05 UTC, raushan303 commented on src/components/Inputs/Dropdown/Dropdown.js
> +    withCreate,
i think we have added eslint hook recently 
so if we are not adding variable using inside hook as dependency, It gives eslint error like
`React Hook React.useEffect has a missing dependency: 'withMultiple'. Either include it or remove the dependency array `
since i was working on this file so i was getting this eslint error

2021-07-19 06:06 UTC, swapnilmisal commented
@raushan303 A jest unit test is required for this bug fix.

2021-07-19 06:23 UTC, raushan303 commented on src/components/Inputs/Dropdown/Dropdown.js
>      // the delay is non-consequential as it's only there when the input resets
@swapnilmisal i already have read this and i am also not in fever to use setTimeOut 
as it was already implemented that way, so i thought whoever implemented that way must have reason to use this.

https://stackoverflow.com/questions/17769005/onclick-and-onblur-ordering-issue
here i saw the concerns of people about  setTimeOut implementation, they are pointing out some cases which is already handled in our implementation 

but we can not be sure that it will work on every device
so if we are not okay with this implementation then i will use another method.

2021-07-20 06:22 UTC, swapnilmisal requested changes

2021-07-20 06:22 UTC, swapnilmisal commented on src/components/Inputs/Dropdown/__tests__/DropdownOption.test.js
> +  const mockFn = jest.fn();
Write in a comment, what we are testing.

2021-07-20 06:22 UTC, swapnilmisal commented on src/components/Inputs/Dropdown/__tests__/DropdownOption.test.js
> +  const { getByTestId } = render(component({ onMouseDown: mockFn }));
@raushan303 this really doesn't test, the bug fix that you have proposed in this PR.

2021-07-22 10:55 UTC, sidMulay requested changes

2021-07-22 10:55 UTC, sidMulay commented on src/components/Inputs/Dropdown/Dropdown.js
>      // otherwise it will reset the text to the old value.
Remove this comment if not needed.

2021-07-22 10:55 UTC, sidMulay commented on src/components/Inputs/Dropdown/Dropdown.js
> +    if (text !== firstValueLabel && target && blurCount.current === 1) {
Add a comment explaining what you're doing here.

2021-07-22 10:55 UTC, sidMulay commented on src/components/Inputs/Dropdown/Dropdown.js
> +  const onMouseDown = () => {
Add a comment as to why mouseDown was used.

2021-07-22 11:17 UTC, sidMulay approved these changes

2021-07-22 11:20 UTC, swapnilmisal approved these changes

2021-07-23 10:16 UTC, raushan303 commented on src/components/Inputs/Dropdown/Dropdown.js
> +    withCreate,
these new dependencies are props which won't change, that's why it wasn't added to dependency array
adding now won't cause any issue.

2021-07-26 06:06 UTC, AwadheshJha commented
Working fine. GTG

2021-07-26 06:23 UTC, gopal-virtual approved these changes

2021-07-26 06:26 UTC, merged

2021-11-16 06:06 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: