feat(ui / card component): create card component
hellohaptik/relements pull request #531
Opened 2021-07-28 08:44 UTC by raushan303

### JIRA Ticket

Jira:  [AGCT-1426](https://hello-haptik.atlassian.net/browse/AGCT-1426)

### Changelog
- create card component
- add jest unit test

### Screenshots (if appropriate):
![Screenshot from 2021-07-28 14-13-56](https://user-images.githubusercontent.com/43717503/127292646-f9e6e812-105e-482f-a4d3-1fe35928673a.png)

2021-07-28 09:06 UTC, raushan303 commented
Netlify - https://adoring-archimedes-a15f38.netlify.app/?path=/story/components-ui-card--documentation

2021-07-28 09:39 UTC, swapnilmisal requested changes

2021-07-28 09:39 UTC, swapnilmisal commented on src/components/UI/Card/Card.js
> +const Card = ({ heading, children, ...props }) => {
rename it to rest

2021-07-28 11:57 UTC, sidMulay requested changes

2021-07-28 11:57 UTC, sidMulay commented on src/components/UI/Card/Card.js
> +      {...rest}
rename this to props.

2021-07-28 11:57 UTC, sidMulay commented on src/components/UI/Card/Card.js
> +      </Text>
- If user does not send the heading, don't render the Text component.

2021-07-28 11:57 UTC, sidMulay commented on src/components/UI/Card/__tests__/Card.test.js
> +});
Add a test case when heading is not sent and Text component is not rendered.

2021-07-29 05:53 UTC, sidMulay submitted a review, later dismissed

2021-07-30 05:12 UTC, swapnilmisal requested changes

2021-07-30 05:12 UTC, swapnilmisal commented on src/components/UI/Card/__tests__/Card.test.js
> +import { ChildComponent } from "../Card.storybook.js";
@raushan303 don't import anything from the storybook.

2021-07-30 05:16 UTC, swapnilmisal requested changes

2021-07-30 05:16 UTC, swapnilmisal commented on src/components/UI/Card/__tests__/Card.test.js
> +import { render, fireEvent, cleanup } from "@testing-library/react";
do you need all these imports?

2021-07-30 05:21 UTC, swapnilmisal commented on src/components/UI/Card/__tests__/Card.test.js
> +  const { queryAllByTestId } = render(component({ heading: heading }));
you can write following line..
`const { queryAllByTestId } = render(component({ heading: heading }));`
like this
`const { queryAllByTestId } = render(component({ heading }));`

2021-07-30 12:37 UTC, raushan303 commented on src/components/UI/Card/__tests__/Card.test.js
> +import { ChildComponent } from "../Card.storybook.js";
I need to import these code in .mdx file and test files
so i have put this here. 
I have taken the reference from our code base only, it's been done this way on other places.

2021-07-30 12:45 UTC, swapnilmisal commented on src/components/UI/Card/__tests__/Card.test.js
> +import { ChildComponent } from "../Card.storybook.js";
test files should be in isolation.
because these are unit tests, --> they should not depend on .mdx files.


the existing pattern used in our codebase is not correct.

2021-07-30 12:47 UTC, raushan303 commented on src/components/UI/Card/__tests__/Card.test.js
> +import { ChildComponent } from "../Card.storybook.js";
@swapnilmisal  so what are you suggesting here? should i create new file and put it there??

2021-07-30 13:06 UTC, swapnilmisal approved these changes

2021-08-02 05:45 UTC, sidMulay approved these changes

2021-08-02 06:09 UTC, merged

2021-11-16 06:06 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: