feat(avatar): avatar with icon and initials
hellohaptik/relements pull request #535
Opened 2021-07-30 09:25 UTC by raushan303

### JIRA Ticket

Jira:  [AGCT-1452](https://hello-haptik.atlassian.net/browse/AGCT-1452)

### Changelog
- Avatar with icon and initials

### Screenshots (if appropriate):

![Screenshot from 2021-07-30 14-53-57](https://user-images.githubusercontent.com/43717503/127632153-a18b1347-b9e8-4784-8b5e-ab720d76868e.png)

2021-07-30 09:38 UTC, raushan303 commented
Netlify :- https://naughty-noether-ece781.netlify.app/?path=/story/components-ui-avatar--documentation

2021-07-30 10:23 UTC, swapnilmisal commented
@raushan303 support 
1. add URL and custom width and height.
2. concentrate only on svgs URLs for now...
3. Make stories for the same.

2021-07-30 10:25 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +        <Icon src={icon} prefixClassName="icon" />
@raushan303 support SVG urls.

2021-07-30 10:27 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +    <Wrapper data-testid="avatar-wrapper">
@raushan303 can we avoid using Wrapper, and use Box instead.

2021-07-30 10:28 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +};
@raushan303 add a default story for the default state.

2021-07-30 10:38 UTC, mohanhaptik commented on src/components/UI/Avatar/Avatar.js
> +  ${Box} {
why 2 box?

2021-08-03 08:43 UTC, swapnilmisal requested changes

2021-08-03 08:43 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +          onError={() => setIsValidUrl(false)}
wrap it in useCallback

2021-08-03 08:43 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +  url: "",
default props to initials???

2021-08-03 08:43 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +        <Box data-testid="avatar-box" style={{ ...AvatarSize, ...BoxStyle }}>
can you avoid passing these props, in this way, because it creates a new object on every render.

2021-08-03 08:43 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +        <Box data-testid="avatar-box" style={{ ...AvatarSize, ...BoxStyle }}>
That could trigger another re-render because the style object is changed.

2021-08-03 08:43 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +        <Box data-testid="avatar-box" style={{ ...AvatarSize, ...BoxStyle }}>
consider creating a styled component.

2021-08-03 08:43 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +        <img
add some loading state, or empty state, that should hold until the image until it gets downloaded.

2021-08-04 09:36 UTC, mohanhaptik approved these changes

2021-08-04 10:02 UTC, swapnilmisal requested changes

2021-08-04 10:02 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +        <IntialsBox data-testid="avatar-box" style={AvatarSize}>
use examples where props are used, to set styles...

meaning, you should pass, e.g. size prop to `<InitialBox height=size width=size/>` component, and based on that prop the style should get changed...

there are some examples, where such a thing is used...
you can refer to the code in the repository...

to give you a gist, at the time of declaration of InitalBox, 
the styles should be a function, of which the signature could look like,
{
...
height: (props) => props.height,
width: (props) => props.width,
...
}

^^ this should work

2021-08-05 04:50 UTC, swapnilmisal requested changes

2021-08-05 04:50 UTC, swapnilmisal commented on src/components/UI/Avatar/__tests__/Avatar.test.js
> -  expect(queryAllByTestId("avatar-box")[0].style.height).toBe("40px");
why did you remove these tests?

2021-08-05 05:02 UTC, raushan303 commented on src/components/UI/Avatar/__tests__/Avatar.test.js
> -  expect(queryAllByTestId("avatar-box")[0].style.height).toBe("40px");
if i am passing height, width as props then it's not accessible with queryAllByTestId("avatar-box")[0].style.height 
in this case i am geeting value of height width "" (empty string)
it's only accessible if i pass directly as style object

2021-08-05 05:05 UTC, swapnilmisal commented on src/components/UI/Avatar/__tests__/Avatar.test.js
> -  expect(queryAllByTestId("avatar-box")[0].style.height).toBe("40px");
there are other methods to find the height, of the element, using DOM APIs you can explore those.

2021-08-05 05:55 UTC, swapnilmisal requested changes

2021-08-05 05:55 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +  backgroundColor: colors.grey.neon,
use colors from props.theme.colors

2021-08-05 05:55 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +import { colors } from "@src/Theme/colors";
we don't need to import this

2021-08-05 05:55 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +            style={TextStyle}
<Text
   variant="h3.semi-bold"
   textTransform=""uppercase"
/>

doesn't this work...

2021-08-05 05:57 UTC, swapnilmisal requested changes

2021-08-05 05:57 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +const BoxStyle = props => ({
also, keep these StyledComponents in a separate file, and then import them into the `Avatar` component.

2021-08-05 07:23 UTC, raushan303 commented on src/components/UI/Avatar/Avatar.js
> +            style={TextStyle}
no i tried, it's not working this way

2021-08-05 07:24 UTC, raushan303 commented on src/components/UI/Avatar/__tests__/Avatar.test.js
> -  expect(queryAllByTestId("avatar-box")[0].style.height).toBe("40px");
created ticket for this, will take it up this later 
https://hello-haptik.atlassian.net/browse/AGCT-1468

2021-08-05 08:12 UTC, swapnilmisal commented on src/components/UI/Avatar/Avatar.js
> +            style={TextStyle}
@sidMulay @gopal-virtual 

is this intentional? if yes then what is the rationale?

2021-08-05 08:52 UTC, gopal-virtual commented on src/components/UI/Avatar/Avatar.js
> +            style={TextStyle}
Not supported by styled system out of box, coz it can be achieved via js

2021-08-05 09:54 UTC, swapnilmisal commented on src/components/UI/Avatar/styledComponents.js
> +  textTransform: "uppercase",
instead of exporting a style object, export a styledComponent.
something like, UppercaseText

2021-08-05 11:55 UTC, swapnilmisal approved these changes

2021-08-05 14:39 UTC, mohanhaptik approved these changes

2021-08-05 15:25 UTC, merged

2021-11-16 06:06 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: