feat(alertdialog): create alert dialog
hellohaptik/relements pull request #536
Opened 2021-08-03 11:39 UTC by raushan303

### JIRA Ticket

Jira:  [AGCT-1434](https://hello-haptik.atlassian.net/browse/AGCT-1434)

### Changelog
- Alert Dialog

### Screenshots (if appropriate):
![Screenshot from 2021-08-03 13-17-43](https://user-images.githubusercontent.com/43717503/128009106-35be02ca-d45e-4b20-a2c8-5ea642dbecb2.png)
![Screenshot from 2021-08-03 17-08-59](https://user-images.githubusercontent.com/43717503/128009199-e96b8394-1f11-4d40-98cb-86f497a05438.png)
![Screenshot from 2021-08-03 17-09-15](https://user-images.githubusercontent.com/43717503/128009216-42ea002a-fd57-4064-8520-432b49061a3c.png)

2021-08-03 15:52 UTC, raushan303 commented
Netlify:- https://infallible-golick-5965d3.netlify.app/?path=/story/components-overlays-alertdialog--documentation

2021-08-05 05:17 UTC, yashasvi13 submitted a review, later dismissed

2021-08-05 05:53 UTC, sidMulay requested changes

2021-08-05 05:53 UTC, sidMulay commented on src/components/Overlays/AlertDialog/AlertDialog.js
> +const AlertDialog = ({
Can you rename the component as `ConfirmDialog`? 

- Alert is when you want to indicate some result of an action, this seems more to me like you're taking an input from the user via the dialog.
- Alert also features success, warning and error variants

2021-08-05 05:53 UTC, sidMulay commented on src/components/Overlays/AlertDialog/AlertDialog.js
> +          </Box>
- What happens when `primaryActionText` and `secondaryActionText`, both are not sent by the props?
- What happens user sends `primary` or `secondary` action text but does not send its action?

2021-08-05 05:53 UTC, sidMulay commented on src/components/Overlays/AlertDialog/AlertDialog.js
> +          <Box justifyContent="center" marginTop="16px">
This should be rendered when atleast one: primary or secondary actions are provided.

2021-08-05 05:53 UTC, sidMulay commented on src/components/Overlays/AlertDialog/AlertDialog.js
> +                {primaryActionText}
Don't rely on user's input, set a default value to this. Use user's prop only when its present.

2021-08-05 05:53 UTC, sidMulay commented on src/components/Overlays/AlertDialog/styledComponents.js
> +  padding: "12px 24px",
Use contracts from `space` here.
Try to use as many values as you can from the design system.

2021-08-05 11:46 UTC, raushan303 commented on src/components/Overlays/AlertDialog/AlertDialog.js
> +const AlertDialog = ({
I have renamed it with Dialog, so later maybe we can use it as alert dialog

2021-08-05 11:49 UTC, raushan303 commented on src/components/Overlays/AlertDialog/AlertDialog.js
> +          </Box>
now i have added default text for Yes to `primaryActionText` and No to `secondaryActionText`
have removed the secondaryAction will be using onClose only with secondaryAction
to primaryAction default empty function `() => {}` is being passed so nothing will happen if primaryAction is not passed

2021-08-05 11:50 UTC, raushan303 commented on src/components/Overlays/AlertDialog/AlertDialog.js
> +          <Box justifyContent="center" marginTop="16px">
Now we have default text so this should be fine

2021-08-06 05:43 UTC, sidMulay commented on src/components/Overlays/AlertDialog/AlertDialog.js
> +          </Box>
If that's the case, we should keep the `primaryAction` as a required prop I feel.

2021-08-06 05:46 UTC, sidMulay approved these changes

2021-08-06 06:25 UTC, yashasvi13 approved these changes

2021-08-06 06:30 UTC, merged

2021-11-16 06:05 UTC, gopal-virtual commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.3.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: