feat(emptyscreen): Empty Screen for Showing Errors or Blank Pages
hellohaptik/relements pull request #553
Opened 2021-10-12 07:52 UTC by ChiragJain-Haptik

### JIRA Ticket

Jira:  [BB-5196](https://hello-haptik.atlassian.net/browse/BB-5196)

--

### Changelog

- An Empty Screen for showing errors and blank pages.
- One can add Title, Subtitle and Icon.
- It will take the complete width of parent div.

--

### Design
- [Design Link](https://www.figma.com/file/yTavkdrfIsMctbOVtHy02W/Master-Prototype?node-id=523%3A2549) - Build(CS) 6.12

### Screenshots:
![image](https://user-images.githubusercontent.com/88431229/136914727-a1ebfb76-1941-474d-ad0c-b7c42502f9ba.png)

2021-11-08 13:04 UTC, sidMulay commented on src/components/UI/EmptyScreen/StyledEmptyScreen.js
> +  display: "table",
Why have we used `table` here?

2021-11-09 04:58 UTC, ChiragJain-Haptik commented on src/components/UI/EmptyScreen/EmptyScreen.js
> +const EmptyScreen = ({ title, subtitle, icon }) => {
Yes, right
Can you suggest a name?

2021-11-09 05:00 UTC, ChiragJain-Haptik commented on src/components/UI/EmptyScreen/EmptyScreen.js
> +        <IconBox src={icon} />
I have kept icon as compulsory. This is discussed with Shahnawaz, so he said to keep that compulsory to show the message with more details.

2021-11-09 05:00 UTC, ChiragJain-Haptik commented on src/components/UI/EmptyScreen/EmptyScreen.js
> +            {title}
Yes, title is also compulsory

2021-11-09 05:04 UTC, ChiragJain-Haptik commented on src/components/UI/EmptyScreen/StyledEmptyScreen.js
> +  display: "table",
To make the icon position always center

2021-11-09 06:16 UTC, ChiragJain-Haptik commented on src/components/UI/EmptyScreen/EmptyScreen.js
> +          </Box>
Done

2021-11-09 06:16 UTC, ChiragJain-Haptik commented on src/components/UI/EmptyScreen/StyledEmptyScreen.js
> +const zIndex = 999999999;
Yes

2021-11-09 06:19 UTC, sidMulay submitted a review, later dismissed

2021-11-09 06:34 UTC, Neha0290 approved these changes

2021-11-09 07:06 UTC, gopal-virtual requested changes
This is very specific to Haptik, adding it to helpers would make more sense.

2021-11-09 07:06 UTC, gopal-virtual commented on src/components/UI/EmptyScreen/EmptyScreen.js
> +        <IconBox src={icon} />
print a friendly error if not passed.

2021-11-09 07:06 UTC, gopal-virtual commented on src/components/UI/EmptyScreen/StyledEmptyScreen.js
> +import styled from "styled-components";
Don't treat styled components as alien, they are part of the component, keep it in related files. Or name the file as helperComponent.

2021-11-09 09:07 UTC, ChiragJain-Haptik commented on src/components/UI/EmptyScreen/StyledEmptyScreen.js
> +import styled from "styled-components";
Renamed the file

2021-12-27 14:20 UTC, closed without merging