feat: File input themed variant added
hellohaptik/relements pull request #568
Opened 2022-01-02 06:38 UTC by murtazamzk

### JIRA Ticket

Jira:  BB-4282

2022-01-04 05:40 UTC, gopal-virtual approved these changes

2022-01-04 05:41 UTC, gopal-virtual requested changes
add tests

2022-01-05 11:25 UTC, gopal-virtual approved these changes

2022-01-05 11:30 UTC, ChiragJain-Haptik approved these changes

2022-01-05 11:35 UTC, merged

2022-07-07 06:19 UTC, gopal-virtual commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.4.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: