feat(modal): Themed Modal with Header and Footer
hellohaptik/relements pull request #575
Opened 2022-01-25 09:19 UTC by ChiragJain-Haptik

### JIRA Ticket

Jira:  [BB-6039](https://hello-haptik.atlassian.net/browse/BB-6039)

--

### Changelog
Themed Modal Added.
- Optional props for Header and Footer.
- Scrollable body if the content is long.
- Styled the scroll for the body content.

--

### Screenshots (if appropriate):
<img width="547" alt="image" src="https://user-images.githubusercontent.com/88431229/150948092-4d968272-0aa4-485c-9ee3-72260fcd139e.png">

2022-01-27 10:24 UTC, murtazamzk approved these changes

2022-01-28 06:25 UTC, sidMulay requested changes

2022-01-28 06:25 UTC, sidMulay commented on src/components/Overlays/Modal/Modal.js
> +          )}
{!noOverlay && ... }

2022-01-28 06:25 UTC, sidMulay commented on src/components/Overlays/Modal/ThemedModal.js
> +  maxHeight: "calc(90vh - 100px)",
Why 90vh?

2022-01-28 06:25 UTC, sidMulay commented on src/components/Overlays/Modal/Modal.js
> +            {footer && <FooterWrapper>{footer}</FooterWrapper>}
The font within Header, Body and Footer should be Proxima Nova (as per our design)

2022-01-28 06:57 UTC, ChiragJain-Haptik commented on src/components/Overlays/Modal/ThemedModal.js
> +  maxHeight: "calc(90vh - 100px)",
So that modal doesn't occupy the whole height.
It will not look that good if modal touched the window.
That's why kept 10vh margin for top and bottom.

2022-01-28 07:03 UTC, ChiragJain-Haptik commented on src/components/Overlays/Modal/Modal.js
> +          )}
Done

2022-01-28 07:03 UTC, ChiragJain-Haptik commented on src/components/Overlays/Modal/Modal.js
> +            {footer && <FooterWrapper>{footer}</FooterWrapper>}
Done

2022-01-28 10:38 UTC, sidMulay commented on src/components/Overlays/Modal/ThemedModal.js
> +  maxHeight: "calc(90vh - 100px)",
Handle that with margin - rather than this.

2022-01-31 08:12 UTC, sidMulay approved these changes

2022-01-31 09:11 UTC, yashasvi13 approved these changes

2022-01-31 10:29 UTC, merged

2022-07-07 06:18 UTC, gopal-virtual commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.4.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: