feat(Icon): new icons
hellohaptik/relements pull request #610
Opened 2022-06-27 08:39 UTC by shailenderPathi

### JIRA Ticket

Jira:  https://hello-haptik.atlassian.net/browse/AN-2514

--

### Changelog

- New icons set is added
- colour can be modified for single coloured icons.
- disabled and hover effect is added

--

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/98324304/175896956-3a78d3ca-d2de-40b0-b83f-f583be12292b.png)

2022-06-28 05:24 UTC, ChiragJain-Haptik requested changes

2022-06-28 05:24 UTC, ChiragJain-Haptik commented on src/components/UI/Icon/Icon.js
> +      tooltip,
If we're giving tooltip on the icons then can we also add support of attachTo?
Please confirm this once with Gopal.

2022-06-28 05:24 UTC, ChiragJain-Haptik commented on src/components/UI/Icon/Icons/AIRecommendationsIcon.js
> +          fill={get(colors, props.iconColor, "#464646")}
Can we use **#464646** code from relements? Its code is `colors.grey.deep`.
Same for other places where you have used this.

2022-06-28 05:34 UTC, shailenderPathi commented on src/components/UI/Icon/Icon.js
> +  const NewIcon = typeof src === "string" && getNewIcon(src);
The main intent of new component was to render new icons which would support colour property. If custom svg is passed then it would be rendered inside old component as we cant alter any colours of it

2022-06-28 05:38 UTC, ChiragJain-Haptik commented on src/components/UI/Icon/Icon.js
> +  const NewIcon = typeof src === "string" && getNewIcon(src);
Okay got it and support of extra small icons is there for old icons as well right?

2022-06-28 05:40 UTC, shailenderPathi commented on src/components/UI/Icon/Icon.js
> +  const NewIcon = typeof src === "string" && getNewIcon(src);
yes it will support. i will edit the .mdx file

2022-06-28 05:51 UTC, ChiragJain-Haptik requested changes

2022-06-28 05:51 UTC, ChiragJain-Haptik commented on src/components/UI/Icon/IconWrapper.js
> +      <WithTooltip
Use themed tooltip (Newer version)

2022-06-28 07:27 UTC, shailenderPathi commented on src/components/UI/Icon/Icon.js
> +      tooltip,
@gopal-virtual can you pls confirm if we icons tooltip need to support attachTo prop

2022-06-28 12:15 UTC, sidMulay requested changes

2022-06-28 12:15 UTC, sidMulay commented on src/components/UI/Icon/utils/getIcon.js
> +const SmartSkill = React.lazy(() => import("icons/smartSkill.svg"));
Create a util function and invoke that instead for all the icons rather than repeating lazy load on each line. Pass the icon path as the parameter.

2022-06-28 12:15 UTC, sidMulay commented on src/components/UI/Icon/utils/util.js
> +export function get(object, path, value) {
Rename this to a more readable name

2022-06-29 09:02 UTC, gopal-virtual requested changes

2022-06-29 10:38 UTC, ChiragJain-Haptik commented on src/components/UI/Icon/Icon.js
> +      tooltip,
okay

2022-06-29 10:41 UTC, shailenderPathi commented on src/components/UI/Icon/utils/getIcon.js
> +const SmartSkill = React.lazy(() => import("icons/smartSkill.svg"));
common util is not supporting

2022-07-07 08:14 UTC, yashasvi13 submitted a review, later dismissed

2022-07-07 08:19 UTC, gopal-virtual approved these changes

2022-07-07 08:24 UTC, sidMulay requested changes

2022-07-07 08:24 UTC, sidMulay commented on config/icons.js
> +      "src/components/UI/Icon/MultiColouredIcons/SmartSkillIcon",
Define base paths for both left-hand and right-hand arguments within constant.

```
const ICON_PATHS = { MULTI_COLORED_BASE: 'ui/multiColouredIcons/', MULTI_COLORED_FROM: 'src/components/UI/Icon/MultiColouredIcons/', ... }

export const MultiColouredIconExports = { [`${ICON_PATHS.MULTI_COLORED_BASE}/SmartSkill`]: `${ICON_PATHS.MULTI_COLORED_FROM}/SmartSkillIcon` }
```

Something readable like that. Your source of truth will be in one place and might help in organising rest.

2022-07-07 08:24 UTC, sidMulay commented on config/icons.js
> +    "ui/icons/ArrowDownIcon": "src/components/UI/Icon/Icons/ArrowDownIcon",
Same as above. Keep adding to ICON_PATHS

2022-07-07 10:04 UTC, sidMulay approved these changes

2022-07-07 10:05 UTC, ChiragJain-Haptik approved these changes

2022-07-07 10:06 UTC, merged

2022-07-29 07:22 UTC, gopal-virtual commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.5.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: