feat(animate-api): add support for exit animation
hellohaptik/relements pull request #613
Opened 2022-06-29 06:27 UTC by sidMulay

### JIRA Ticket

Jira:  [BB-7912](https://hello-haptik.atlassian.net/browse/BB-7912)

---

### Changelog

- Add support for exit animations in Animate API
- Fix export

Test link: https://sid-relements.netlify.app/?path=/story/design-system-helpers--animate

2022-06-30 11:23 UTC, sidMulay commented on src/components/Animate/animate.storybook.js
> +        <Text>{renderAnimations()}</Text>
This design is to be improved, just kept here as a placeholder.

2022-07-05 06:10 UTC, gopal-virtual requested changes

2022-07-05 06:10 UTC, gopal-virtual commented on config/exports.js
> +  'components/animate': 'src/components/Animate/index.js',
keep it under `Layout`

2022-07-05 06:10 UTC, gopal-virtual commented on src/Theme/animateAPI.js
> +        if (
if/else is not scalable, use a map instead

2022-07-05 11:43 UTC, yashasvi13 approved these changes

2022-07-05 11:57 UTC, merged

2022-07-07 06:18 UTC, gopal-virtual commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.4.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: