feat(xdk): changes for xdk
hellohaptik/relements pull request #624
Opened 2022-08-17 06:22 UTC by shailenderPathi

### Changelog

- disabled property for time and date inputs
- New XDK Modal
- Search dropdown

2022-08-18 10:44 UTC, ChiragJain-Haptik requested changes

2022-08-18 10:44 UTC, ChiragJain-Haptik commented on src/components/Inputs/Dropdown/Dropdown.js
> +  containerHeight,
Please specify in what scenario this prop is required.

2022-08-18 10:44 UTC, ChiragJain-Haptik commented on src/components/Inputs/DropdownSearch/Components/DropdownSearch.js
> +export default function DropdownSearch({
Can you rename it to something related to the function it is performing?

Also, I had looked into the component, we are having a modal inside of it. Can we create this a separate component and can call it inside the modal wherever it is required? It'll increase the use-cases of this component.

2022-08-18 10:44 UTC, ChiragJain-Haptik commented on src/components/Inputs/DropdownSearch/Components/DropdownSearchLoading.js
> +        {/* <String id="START_TYPING_TO_SEARCH" /> */}
This you can remove I think.

2022-08-18 10:44 UTC, ChiragJain-Haptik commented on src/components/Inputs/DropdownSearch/DropdownSearchLoading.scss
> +$loader-size: 20px;
move this constant to top

2022-08-18 10:44 UTC, ChiragJain-Haptik commented on src/components/Inputs/DropdownSearch/hooks.js
> +  const search = text => {
Confirm once with Ankur or Gopal, can we add debouncer over here

2022-08-18 10:44 UTC, ChiragJain-Haptik commented on src/components/Inputs/Text/Text.js
> +const PrefixComponentWrapper = styled("div")({
Check once on storybook for this variation.
Also, check the spacing for the prefix icon.
<img width="316" alt="image" src="https://user-images.githubusercontent.com/88431229/185375186-f2201c1a-fea7-48d8-a293-b4bea5cb8ca3.png">

2022-08-18 10:44 UTC, ChiragJain-Haptik commented on src/components/Overlays/XDKModal/XDKModal.js
> +  borderBottom: "1px solid #D5D5D5",
haptik.grey colour code for this.

2022-08-18 10:44 UTC, ChiragJain-Haptik commented on src/components/Overlays/XDKModal/XDKModal.js
> +  borderBottom: "1px solid #D5D5D5",
also, check other places where you can use the existing themed variables.

2022-08-19 06:59 UTC, gopal-virtual requested changes

2022-08-19 06:59 UTC, gopal-virtual commented on src/components/Inputs/Date/Date.js
> +    const { containerHeight } = this.props;
use `attachTo` DOM element to extract the height

2022-08-19 06:59 UTC, gopal-virtual commented on src/components/Inputs/Dropdown/components/Options/Options.js
> +    if (inputRef && inputRef.current) {
check the git history, why was it added? Afaik, it was a bug fix.

2022-08-19 06:59 UTC, gopal-virtual commented on src/components/Inputs/DropdownSearch/Components/DropdownSearch.js
> +export default function DropdownSearch({
move it to helpers

2022-08-19 06:59 UTC, gopal-virtual commented on src/components/Inputs/Text/Text.js
> +  prefixComponent,
call it `icon` & `iconPosition`. Also, accommodate different sizes or restrict the size if you want.

2022-08-19 10:26 UTC, shailenderPathi commented on src/components/Inputs/Date/Date.js
> +    const { containerHeight } = this.props;
This cant be done for date as its using tooltip internally for displaying the calendar.
this explicitly needs container height
![image](https://user-images.githubusercontent.com/98324304/185599135-f2e7b39b-cb31-4595-b0fc-0f1fc83c5c92.png)

2022-09-07 08:08 UTC, ChiragJain-Haptik requested changes

2022-09-07 08:08 UTC, ChiragJain-Haptik commented on src/components/Inputs/Text/Text.js
> +const PrefixComponentWrapper = styled("div")({
Instead of repeating everything for PrefixComponentWrapper and PostfixComponentWrapper, you can accept a prop isPrefix and on the basis of that you can give the value to left or right

2022-09-07 08:40 UTC, shailenderPathi commented on src/components/Inputs/Text/Text.js
> +const PrefixComponentWrapper = styled("div")({
added

2022-09-07 08:42 UTC, ChiragJain-Haptik approved these changes

2022-09-07 12:38 UTC, gopal-virtual approved these changes

2022-09-07 12:38 UTC, ChiragJain-Haptik approved these changes

2022-09-07 12:40 UTC, merged

2022-09-30 10:53 UTC, gopal-virtual commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.6.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: