feat: added netlify-cli package and script to generate a storybook link
hellohaptik/relements pull request #630
Opened 2022-09-21 12:57 UTC by direshp

### JIRA Ticket

Jira:  [BB-8497](https://hello-haptik.atlassian.net/browse/BB-8497)

### Changelog
- added netlify-cli package and script to generate a storybook link

2022-09-22 06:58 UTC, sidMulay requested changes

2022-09-22 06:58 UTC, sidMulay commented on package.json
> +    "typescript": "^3.9.7",
Why was typescript upgrade needed?

2022-09-22 07:05 UTC, direshp commented on package.json
> +    "typescript": "^3.9.7",
There was no typescript update done and the version is the same as well but its showing there is some change not sure why.

2022-09-22 07:06 UTC, direshp commented on package.json
> +    "typescript": "^3.9.7",
I think only the line number where the package was mentioned is changed.

2022-09-22 07:27 UTC, ChiragJain-Haptik approved these changes

2022-09-22 08:02 UTC, sidMulay approved these changes

2022-09-22 10:17 UTC, merged

2022-09-30 10:53 UTC, gopal-virtual commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/relements/v/2.6.0)
- [GitHub release](https://github.com/hellohaptik/relements/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: